syn match MyBadSemiColon /;\s*[^\%]\&./
"syn match MySpecialChar /;\s*\_$\|;\s*%\&./
syn match MySpecialChar /,\|;\s*\_$\|;\s*\/\&.\|\(for.*\)\@<=;/
syn match MyBrac /{\|}\|(\|)/
"syn match MyOps /=\|<\|>\|&\||\|+\|-\|*\|\.\|:\|!\|\/\(\/\|*\)\@!/
syn match MyOps /=\|<\|>\|&\||\|+\|-\|*\|\.\|:\|!\|\~\|\/\(\/\|*\)\@!/
"syn match MyAccess /\[\|\]\|\s*_\|\(=\|<\|>\|&\||\|+\|-\|*\|\.\|:\|!\|\/\/\@!\)\@=_/
syn match MyAccess /\[\|\]\|\(=\|<\|>\|&\||\|+\|-\|*\|\.\|:\|!\|\~\|\/\/\@!\)\@=_/
syn match MyAffect /\(\~\|=\|<\|>\|\)\@<!==\@!\|++\|--/
